### ISSUE TITLE
I have Rise5.98 Can you crack this???

### ISSUE THREAD

**Issue by NoCheatUltra** [jeremypelletier/tenacity-unlicensed#1]
This is Rise5.98 file
https://www.mediafire.com/file/5lqu9wmjmjxxv56/Rise5.98.zip/file

plz crack!!!

**Comment by CodeKid0** [comment]
> This is Rise5.98 file
> https://www.mediafire.com/file/5lqu9wmjmjxxv56/Rise5.98.zip/file
> 
> plz crack!!!

Allah creck 😳

**Comment by jeremypelletier** [comment]
We are waiting for Rise 6
