### ISSUE TITLE
Doesn't launch

### ISSUE THREAD

**Issue by dremonq** [jeremypelletier/tenacity-unlicensed#2]
69

**Comment by jeremypelletier** [comment]
Only supports windows x64 I believe. Make sure you have "-noverify" in your launch arguments.

**Comment by dremonq** [comment]
> Only supports windows x64 I believe. Make sure you have "-noverify" in your launch arguments.

I did put -noverify and doesn't work

**Comment by jeremypelletier** [comment]
Are you on a x64 Windows machine? No one else is having issues.

**Comment by dremonq** [comment]
> Are you on a x64 Windows machine? No one else is having issues.

yes it's x64
